### ISSUE TITLE
'Again' cards not reported!

### ISSUE THREAD

**Issue by TheDemystifier** [trgkanki/remaining_time#26] opened 2020-11-14 10:37 UTC
# Bug report

## Describe the bug

> You press 'again' on a card while reviewing, it's logged as 'good'. Always. 

## Reproduction step

> Steps to reproduce the behavior:

1. Go to 'any card to review'
2. Click on 'again'
3. Scroll down to 'HTML code OR debug'
4. See how it says 'rev-good'

## Expected behavior

> Again cards should show up red for example, hard cards a different shade, etc..

## Actual behavior

> Again cards are reported as good.

## Anki/OS versions

- OS: Windows 10 Pro 64bits
- Anki Version 2.1.24 (359b9f5c)

## Additional context

Here are the logs: https://pastebin.com/HWbzPxX0
Here's the rendered HTML: https://pastebin.com/QfPtYtw3

**Comment by phu54321** [comment] 2020-11-14 12:00
Omg if confirmed, will hotfix

**Comment by phu54321** [comment] 2020-11-14 15:14
Fixed via series of commits

![image](https://user-images.githubusercontent.com/775265/99150374-80766900-26d7-11eb-9e0a-8f22da030540.png)

**Comment by phu54321** [comment] 2020-11-14 15:35
Reopening cause, IDK why but the fix interferes with ankidroid.

**Comment by thiswillbeyourgithub** [comment] 2020-11-15 14:42
Don't know if it's related but I notived the other day that no matter what button I pressed it seemed that the "good" button was doing the click animation.

I have nothing else to add sorry.

**Comment by phu54321** [comment] 2020-11-15 15:28
Is the issue fixed on the latest update?

**Comment by TheDemystifier** [comment] 2020-11-16 10:14
> Is the issue fixed on the latest update?

Unfortunately not 🤔, It still registers everything as good. Maybe it's something to do with the version of Anki?
I can post another debug if you want.

**Comment by phu54321** [comment] 2020-11-16 10:27
According to the logs

```
[2020-11-14 11:25:53]   RCC - prev: {"nu":10,"lrn":120,"rev":0}, current: {"nu":10,"lrn":119,"rev":0}
[2020-11-14 11:26:21]   RCC - prev: {"nu":10,"lrn":119,"rev":0}, current: {"nu":10,"lrn":119,"rev":0}
[2020-11-14 11:26:21]   RCC - prev: {"nu":10,"lrn":119,"rev":0}, current: {"nu":10,"lrn":119,"rev":0}
[2020-11-14 11:26:40]   RCC - prev: {"nu":10,"lrn":119,"rev":0}, current: {"nu":10,"lrn":118,"rev":0}
[2020-11-14 11:27:08]   RCC - prev: {"nu":10,"lrn":118,"rev":0}, current: {"nu":10,"lrn":117,"rev":0}
[2020-11-14 11:27:24]   RCC - prev: {"nu":10,"lrn":117,"rev":0}, current: {"nu":10,"lrn":116,"rev":0}
[2020-11-14 11:27:29]   RCC - prev: {"nu":10,"lrn":116,"rev":0}, current: {"nu":10,"lrn":115,"rev":0}
[2020-11-14 11:27:33]   RCC - prev: {"nu":10,"lrn":115,"rev":0}, current: {"nu":10,"lrn":114,"rev":0}
[2020-11-14 11:27:41]   RCC - prev: {"nu":10,"lrn":114,"rev":0}, current: {"nu":10,"lrn":113,"rev":0}
[2020-11-14 11:27:49]   RCC - prev: {"nu":10,"lrn":113,"rev":0}, current: {"nu":10,"lrn":112,"rev":0}
[2020-11-14 11:28:17]   RCC - prev: {"nu":10,"lrn":112,"rev":0}, current: {"nu":10,"lrn":111,"rev":0}
[2020-11-14 11:29:12]   RCC - prev: {"nu":10,"lrn":111,"rev":0}, current: {"nu":10,"lrn":110,"rev":0}
[2020-11-14 11:29:15]   RCC - prev: {"nu":10,"lrn":110,"rev":0}, current: {"nu":10,"lrn":109,"rev":0}
[2020-11-14 11:29:23]   RCC - prev: {"nu":10,"lrn":109,"rev":0}, current: {"nu":10,"lrn":108,"rev":0}
```

Even if you pressed 'again', it seems like those cards aren't going to review queue. If this related to your deck settings?

**Comment by TheDemystifier** [comment] 2020-11-16 15:06
Confirmed! Deck settings are to blame. This is what I've tried:

1. Disabled all other addons to prevent any kind of intervention or involvement.
2. Restarted Anki
3. Changed settings of a deck to 'Default'
4. Worked fine, recognized 'Again' cards.

When I change the settings back, it stops working! Does the addon reference the default settings by default?

Here are the settings I used.
[New Cards](https://i.imgur.com/dqrLg5B.png)
[Reviews](https://i.imgur.com/JCR6reo.png)
[Lapses](https://i.imgur.com/0kCRWgB.png)

**Comment by phu54321** [comment] 2020-11-16 15:22
OK. Let me explain how the addon detects whether you pressed 'good' or 'again.

https://github.com/trgkanki/remaining_time/blob/ef0c7215e570a5a18b10edbdcd0d49a162b946ba/jssrc/updater.ts#L65

Basically it tracks how many cards are left. So, say you have 20 new cards left, 100 reviewed cards to go, and 10 cards currently learning. Let's represent this with 3-numbered tuple. (20, 10, 100). This is in new, learning, and review order.

Say, on (20, 10, 100), you get a review card. You get it wrong. Because I lapsed this card this goes to the learning queue, so the tuple goes to (20, 12, 99).

- review goes down by 1 because I've reviewed a card
- learning goes up by 2 because in my deck settings dictate two learning steps for lapsed cards. (1m 20m)

So this is my settings. But, according to your settings,

- reviews goes down by 1 because you've reviewed a card.
- learning goes up by 0 because, well, you have no learning steps for a lapsed card. Their interval will just go down.

-----

So, why are addon using this method to track 'again' or 'good'? Older version of addons tracked 'again' and 'good' based on the button you pressed. Why use an indirect method?

This is because this addon has been largely re-developed from scratch to **support AnkiDroid**. AnkiDroid provides no method to addon for getting what button the user has pressed. It only provides a way to get those (20, 10,100) numbers. So, to both support AnkiDroid and Anki Desktop with a single code, I've just made a code that tracks those numbers instead of relying on button presses altogether.

So, the addon is using an indirect method to both support Desktop and Mobile environment. Probably I could add support for _no-learning-step-for-lapsed-card_ deck configuration by special-casing it, but really, adding support for special case means more code to bug and break, so I'm a little hesitant to add more features on a mature addon like this.

------

This is the first time I've seen this kind of deck configuration, and I'm not sure if I've figured out your settings correctly. If I'm correct, I'll post a question to Reddit to see if many users are using similar settings to yours, to see if this needs development. ([like this](https://www.reddit.com/r/Anki/comments/jtvx0z/anybody_using_long_learning_steps_for_new_cards/)) Also, due to the nature of how the addon works, Your deck setting won't be supported on mobile.

**Comment by TheDemystifier** [comment] 2020-11-16 16:12
I see! It's okay. The settings I use mimic [SuperMemo 2's algorithm](https://youtu.be/1XaJjbCSXT0?t=1149) (6days initially → 15d → ...). Anyone on the forum would tell you that the default Anki settings are quite lacking. So most 'advanced' used tweak the settings to their liking.

I see how adding exceptional cases would complicate the addon further. If it's only me having this issue, It's okay, you can make changes later on if more people complain.

Thanks for your time.

**Comment by phu54321** [comment] 2020-11-16 16:17
Oh you're so using interval longer than a day.

Ok I've seen many using this system.

**Closed** 2021-06-27 05:44 UTC
Labels: bug, discussion, wontfix
