### ISSUE TITLE
Add-On not working on Anki Version ⁨23.12.1

### ISSUE THREAD

**Issue by Vulkatnos** [trgkanki/remaining_time#80] opened 2024-01-23 12:45 UTC
Hello, first of all thank you for sharing this amazing add-on, sadly since Anki updated it is no longer working. 

## Describe the bug

When opening Anki after installing the Add-On one is greated with a error message, sometimes this error message only pops up once you enter "study-mode"

## Reproduction step

1. Update Anki to the newest Version.
2. Install Add-On
3. Close and reopen Anki

## Expected behavior

Normal function as described in the add-on discription

## Actual behavior

Error Message, Add-On not functional

## Anki/OS versions

- Windows 10
- Anki: Version ⁨23.12.1

## Additional context

I updated to the new anki version before installing the add-on, therefor it has not yet worked on my device. However as the anki comment section is filled with reports of the add-on not working after updating, when it did before I am inclined to believe that this is the issue

**Comment by phu54321** [comment] 2024-01-23 13:07
Duplicate of #78

See https://github.com/trgkanki/remaining_time/issues/78#issuecomment-1906025715 for possible release

**Closed** 2024-01-23 13:08 UTC
Labels: bug
