### ISSUE TITLE
not working in newest anki update.

### ISSUE THREAD

**Issue by FH10003** [trgkanki/remaining_time#79] opened 2024-01-10 10:48 UTC
# Addon not working

## Describe the bug

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-13.5-arm64-arm-64bit

Traceback (most recent call last):
  File "aqt.webview", line 50, in cmd
  File "aqt.webview", line 157, in _onCmd
  File "aqt.webview", line 680, in _onBridgeCmd
  File "_aqt.hooks", line 5415, in __call__
  File "/Users/fatimahasan/Library/Application Support/Anki2/addons21/1508357010/utils/JSCallable.py", line 29, in _onBridgeMessage
    ret = func(*argList)
  File "/Users/fatimahasan/Library/Application Support/Anki2/addons21/1508357010/jsapi/remainingCardCount.py", line 10, in getCurrentRemainingCardCount
    if reviewer.hadCardQueue:
AttributeError: 'Reviewer' object has no attribute 'hadCardQueue'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AMBOSS Official  Medical School Step  Shelf Study Resource ['1044112126', 2999-01-01T00:00, 'None', mod]
Advanced Browser ['874215009', 2023-10-21T15:34, 'None', '']
AnkiBrain AnkiChatGPT - GPT-4 GPT 35 with auto-cards and document analysis ['1915225457', 2023-12-08T00:23, 'None', '']
Button Colours Good Again ['2494384865', 2022-09-27T11:18, 'None', '']
Congrats Confetti ['206062158', 2023-01-17T04:02, 'None', '']
Countdown To Events and Exams ['1143540799', 2022-06-27T12:50, 'None', '']
Custom Background Image and Gear Icon ['1210908941', 2023-04-19T02:19, 'None', mod]
FSRS4Anki Helper ['759844606', 2024-01-06T07:46, 'None', '']
Image Occlusion Enhanced ['1374772155', 2022-04-09T08:15, 'None', '']
Life Drain ['715575551', 2023-12-01T05:53, 'None', mod]
Puppy Reinforcement ['1722658993', 2023-11-16T12:59, 'None', '']
Remaining time for Anki 21 ['1508357010', 2020-12-13T14:14, '20.12.13i151', '']
Review Heatmap ['1771074083', 2022-06-30T02:43, 'None', '']
Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2022-12-16T11:24, 'None', '']

===IDs of active AnkiWeb add-ons===
1044112126 1046608507 1143540799 1210908941 1374772155 1508357010 1722658993 1771074083 1915225457 206062158 2494384865 715575551 759844606 874215009

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

## Reproduction step

> Steps to reproduce the behavior:

## Expected behavior

> A clear and concise description of what you expected to happen.

## Actual behavior

> If applicable, add screenshots to help explain your problem.

## Anki/OS versions

- OS: *[ex: macOS Catalina, Windows 10, Ubuntu 18.04]*
- Anki version *[ex: 2.1.23]*

## Additional context

> Add any other context about the problem here.
please fix it asap

**Comment by phu54321** [comment] 2024-01-10 11:20
Duplicate of #78

Would you test the version uploaded there?

**Closed by phu54321** 2024-01-10 11:20 UTC
Labels: bug
