### ISSUE TITLE
Toggle bar time sensitivity (different than a pause button)/additional config options

### ISSUE THREAD

**Issue by MrAnki** [trgkanki/remaining_time#25] opened 2020-11-12 20:52 UTC
Would love the option to toggle the bar to not slide around based on time, IE based on % completion and all the colors etc. stays the same (sort of like progress bar but with more colors). 
I always get frustrated on days where I start my reviews early then have an activity for a few hours and the progress bar projections get a little weird as it brings the projected time way up, this is fixable with just resetting the bar but obviously I liked like to avoid that so I can have a idea of how far I am in the day in X amount of time 

Second feature is just a config option to add the count of new cards completed that day, IE. New->learning transition not learning->young. I like to do my new cards in batches of about 50-100 but sometimes there is a random uneven number of new cards for the day so the math gets unfortunate. 
Other config options that could be cool (no clue how difficult it would be to add I can't code): Just an option for % of cards complete, Time spent on new/young/mature/learning cards.

**Comment by phu54321** [comment] 2020-11-13 00:29
Seems like a duplicate of #24. Is that correct?

**Comment by MrAnki** [comment] 2020-11-13 00:55
> Seems like a duplicate of #24. Is that correct?

Not exactly, #24 is basically just a pause button for when you're away as I understand it. This would remove the time component all together, so if for example I have 100 cards to complete, each card I do fills x% of the progress bar in the colors we already have. 

Presumably the % fill for each card would be 100/(new+learning+mature+#incorrect) where new/learn/mature count is just stored from either when the reset log button is used or a new day but those wouldn't obviously update throughout the day.

**Comment by phu54321** [comment] 2020-11-13 01:24
This addon is basically about remaining **time**. All other features are strictly accessory.

Use this addon instead.

https://ankiweb.net/shared/info/2091361802

**Comment by MrAnki** [comment] 2020-11-13 01:33
Sure but the time calculation is also messed up for people with a learning step of 25 1440 etc

**Comment by phu54321** [comment] 2020-11-14 04:33
Sorry for bad english :( I wanna check if I've understood your comment correctly

> Would love the option to toggle the bar to not slide around based on time, IE based on % completion and all the colors etc. stays the same (sort of like progress bar but with more colors).

Do you want every question takes the same amount of space regardless of time spent on it?

![image](https://user-images.githubusercontent.com/775265/99139627-d9b1ae80-267d-11eb-834b-e9b4be882cdb.png)

So that 'new' progress just get stacked without existing segments sliding/shrinking/expanding around?

**Comment by MrAnki** [comment] 2020-11-14 23:50
Hi thanks for the update/reply! and what you said at the top is mostly what I am asking. But as you mention the total number of reviews you need to do does change. So each individual 'tick' bar would shrink by 1/(total cards+incorrect-undo). I think I can explain better if I make it into pictures, I will do that tomorrow and reply so hopeful I can make more sense.

**Closed** 2020-12-13 14:14 UTC
Labels: committed
