### ISSUE TITLE
Bar does not show up in Anki 2.1.35-alternative for mac OS X 10.10+

### ISSUE THREAD

**Issue by EngerLar** [trgkanki/remaining_time#30] opened 2020-11-26 12:06 UTC
# Bug report

## Describe the bug

> The remaining time bar is not visible in the alternative updated version of Anki 2.1.35, which works for Mac OS X 10.10+. (I did not update the Mac OS X version, since my MacBook is quite old and new updates make the software very slow.) Since I updated Anki on the newest alternative version, the remaining time bar is not visible any more. However, on the phone the plug in works perfectly even now.

## Reproduction step

> Steps to reproduce the behavior:

1. Go on any deck
2. Click on 'study now'
3. See error (no bar visible)

## Expected behavior

> I would love to be able to see the bar again.

## Actual behavior

> If applicable, add screenshots to help explain your problem.

![grafik](https://user-images.githubusercontent.com/75075913/100348959-fe941300-2fe7-11eb-9a1d-51fe038a620d.png)

## Anki/OS versions

- OS: macOS Sierra Version 10.12.6
- Anki version: 2.1.35-alternative

## Additional context

> Add any other context about the problem here.

**Comment by phu54321** [comment] 2020-12-07 05:16
Not reproduced on macOS catalina, 2.1.35 alternative version. We need more debugging info.

![image](https://user-images.githubusercontent.com/775265/101312181-725ed700-3896-11eb-81aa-cb1ed9fcc6d5.png)

1. Download [AnkiWebView Inspector](https://ankiweb.net/shared/info/31746032) addon
2. Run reviewer.
3. Right-click on the reviewer window and click 'inspect', and on the inspector, open console view.
4. check if there's any error message there.

![image](https://user-images.githubusercontent.com/775265/101312286-b81b9f80-3896-11eb-8ef9-ec49f5b44e0d.png)

**Comment by phu54321** [comment] 2021-01-04 08:19
Closing due to lack of additional info

**Closed by phu54321** 2021-01-04 08:19 UTC
Labels: bug
